### ISSUE TITLE
Uncaught Error: Call to a member function fetchAll()

### ISSUE THREAD

**Issue by herrbischoff** [agentejo/cockpit#1322]
### Environment

```
$ uname -a
FreeBSD vagrant 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64
```
```
$ php -v
PHP 7.4.8 (cli) (built: Aug  6 2020 01:30:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```
```
$ php -m
[PHP Modules]
Core
ctype
date
gd
hash
libxml
mbstring
mysqlnd
pcre
PDO
pdo_sqlite
Reflection
SPL
standard
zip
```

### Issue

0. Installing https://github.com/agentejo/cockpit/archive/master.zip
1. Opening http://10.20.30.40/install
2. Start of installation fails with a white screen. On request, the following error occurs (PHP error log):

```
[13-Aug-2020 14:59:11 UTC] PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /usr/local/www/cockpit/lib/MongoLite/Database.php:183
Stack trace:
#0 /usr/local/www/cockpit/lib/MongoLite/Database.php(219): MongoLite\Database->getCollectionNames()
#1 /usr/local/www/cockpit/lib/MongoLite/Client.php(77): MongoLite\Database->selectCollection()
#2 /usr/local/www/cockpit/lib/MongoHybrid/MongoLite.php(35): MongoLite\Client->selectCollection()
#3 [internal function]: MongoHybrid\MongoLite->getCollection()
#4 /usr/local/www/cockpit/lib/MongoHybrid/Client.php(425): call_user_func_array()
#5 /usr/local/www/cockpit/install/index.php(66): MongoHybrid\Client->__call()
#6 {main}
  thrown in /usr/local/www/cockpit/lib/MongoLite/Database.php on line 183
```

**Comment by raffaelj** [comment]
You also have to install sqlite3, not only pdo_sqlite.

See the Dockerfile for a list of dependencies: https://github.com/agentejo/cockpit/blob/next/Dockerfile#L10

**Comment by 21e8** [comment]
I am riunning this from a docker container and getting the same error
