### ISSUE TITLE
Erro to upload assets

### ISSUE THREAD

**Issue by williamespindola** [agentejo/cockpit#599]
When upload some file on assets menu, this erro return on `/cockpit/assetsmanager/upload` request. The problem is not related with folders permission because the file has been uploaded to `uploads/2017/11/15` directory

```html
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function ColorThief\Image\Adapter\imagecreatefrompng() in /var/www/html/public/cockpit/lib/ColorThief/Image/Adapter/GDImageAdapter.php:47
Stack trace:
#0 /var/www/html/public/cockpit/lib/ColorThief/Image/ImageLoader.php(36): ColorThief\Image\Adapter\GDImageAdapter-&gt;loadFile('/var/www/html/p...')
#1 /var/www/html/public/cockpit/lib/ColorThief/ColorThief.php(177): ColorThief\Image\ImageLoader-&gt;load('/var/www/html/p...')
#2 /var/www/html/public/cockpit/lib/ColorThief/ColorThief.php(136): ColorThief\ColorThief::loadImage('/var/www/html/p...', 10, NULL)
#3 /var/www/html/public/cockpit/modules/Cockpit/Controller/Assets.php(84): ColorThief\ColorThief::getPalette('/var/www/html/p...', 5)
#4 [internal function]: Cockpit\Controller\Assets-&gt;upload()
#5 /var/www/html/public/cockpit/lib/Lime/App.php(1074): call_user_func_array(Array, Array)
#6 /var/www/html/public/cockpit/lib/Lime/App.php(846): Lime\App-&gt;invoke('Cockpit\\Control...', 'upload', Array)
#7 [internal function]: LimeExtra\App- in <b>/var/www/html/public/cockpit/lib/ColorThief/Image/Adapter/GDImageAdapter.php</b> on line <b>47</b><br />
```

**Comment by williamespindola** [comment]
Ok, I got it! I'm missing GD extension.
