### ISSUE TITLE
PDOException on Install

### ISSUE THREAD

**Issue by ajzozakiewicz** [agentejo/cockpit#622]
Getting this error when I try to run the /install step:

```
2017/12/20 00:02:41 [error] 3805#3805: *1684 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/neid-cockpit/lib/MongoLite/Database.php:42
Stack trace:
#0 /var/www/neid-cockpit/lib/MongoLite/Database.php(42): PDO->__construct('sqlite:/var/www...', NULL, NULL, Array)
#1 /var/www/neid-cockpit/lib/MongoLite/Client.php(75): MongoLite\Database->__construct('/var/www/neid-c...', Array)
#2 /var/www/neid-cockpit/lib/MongoLite/Client.php(63): MongoLite\Client->selectDB('cockpit')
#3 /var/www/neid-cockpit/lib/MongoHybrid/MongoLite.php(27): MongoLite\Client->selectCollection('cockpit', 'webhooks')
#4 /var/www/neid-cockpit/lib/MongoHybrid/MongoLite.php(47): MongoHybrid\MongoLite->getCollection('webhooks')
#5 [internal function]: MongoHybrid\MongoLite->find('cockpit/webhook...')
#6 /var/www/neid-cockpit/lib/MongoHybrid/Client.php(420): call_user_func_array(Array, Array)
#7 /var/www/neid-cockpit/modules/Cockpit/webhooks.php(8): MongoHybrid\Client->__call('find', Array)
#8 /var/www/neid-cockpit/modules/Cockpit/bootstrap.php(475" while reading response header from upstream, client: 75.86.210.41, server: brewcitydigital.com, request: "GET /neid-cockpit/install/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "www.brewcitydigital.com"
```

Any help on this would be appreciated.

**Comment by ajzozakiewicz** [comment]
Found the fix... 

Needed to install the proper version of sqllite

```
sudo apt-get install php7.0-sqlite3
```

then restart php

```
sudo systemctl restart php7.0-fpm
```

also see issue 166 for initial issue ... closing issue

**Comment by elhenro** [comment]
I have the same issue on archlinux, but cant seem to fix it by installing [this](https://aur.archlinux.org/packages/php70-sqlite/)

**Comment by joephill11** [comment]
> I have the same issue on archlinux, but cant seem to fix it by installing [this](https://aur.archlinux.org/packages/php70-sqlite/)

i know this is a old post but i was searching online and wanted to post this for anybody else trying to troubleshoot cockpit on arch linux. use a aur helper such as yay and install cockpit-machines through there that just got mine working properly for the virtual machines section. you can also install the other modules this way as well.
