### ISSUE TITLE
Fatal Error, could not install

### ISSUE THREAD

**Issue by diamantisk** [agentejo/cockpit#640]
Dear all,
I tried twice to install cockpit on latest centos with php 7.0 mongodb and nginx but without success. Error log of nginx is as follows:

oot@ctrl ~]# tail -f /var/log/nginx/error.log 
#1 /var/www/snapshot/lib/MongoHybrid/MongoLite.php(53): MongoLite\Cursor->toArray()
#2 [internal function]: MongoHybrid\MongoLite->find('cockpit/webhook...')
#3 /var/www/snapshot/lib/MongoHybrid/Client.php(420): call_user_func_array(Array, Array)
#4 /var/www/snapshot/modules/Cockpit/webhooks.php(8): MongoHybrid\Client->__call('find', Array)
#5 /var/www/snapshot/modules/Cockpit/bootstrap.php(475): include_once('/var/www/snapsh...')
#6 /var/www/snapshot/lib/Lime/App.php(1311): require('/var/www/snapsh...')
#7 /var/www/snapshot/lib/Lime/App.php(1270): Lime\App->bootModule(Object(Lime\Module))
#8 /var/www/snapshot/lib/Lime/App.php(1294): Lime\App->registerModule('cockpit', '/var/www/snapsh...')
#9 /var/www/snapshot/bootstrap.php(146): Lime\App->loadModules(Array)
#10 /var/www" while reading response header from upstream, client: 46.176.227.136, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000"

I think it cant find any SQLite file embedded (no SQLite file exists in any distribution zip file or GitHub).
Of course I will try to solve it by myself somehow, I just asked in case some one of you had already faced the same issue, in order to avoid reinventing the wheel.
The project is a great job in any way.

Regards

**Comment by diamantisk** [comment]
I managed to install it finally by changing the default server connection from sqlite to mongodb (i have locally installed mongodb), as follows: 
//'database'     => [ "server" => "mongolite://".(COCKPIT_STORAGE_FOLDER."/data"), "options" => ["db" => "cockpitdb"] ],
            'database'     => [ "server" => "mongodb://127.0.0.1:27017", "options" => ["db" => "snapshot"] ],

It would be useful mongolite connector to be modified in away in case .sqlite file does not exists to create one on the fly, since in my case all permissions were fine but i always got the above exception.
