### ISSUE TITLE
Errors with uploading files

### ISSUE THREAD

**Issue by JonSnowbd** [agentejo/cockpit#858]
Uploading images makes the bar go from 0 to 100% then fail out. Most times the error is "Something has gone wrong", other times it's "Files failed to uploaded"
in the log its this:
```[Thu Sep 13 07:03:19.998377 2018] [php7:error] [pid 23986] [client 173.252.51.99:56335] PHP Fatal error:  Uncaught Error: Call to undefined function ColorThief\\Image\\Adapter\\imagecreatefromjpeg() in /var/www/html/cockpit/lib/vendor/ksubileau/color-thief-php/lib/ColorThief/Image/Adapter/GDImageAdapter.php:43\nStack trace:\n#0 /var/www/html/cockpit/lib/vendor/ksubileau/color-thief-php/lib/ColorThief/Image/ImageLoader.php(36): ColorThief\\Image\\Adapter\\GDImageAdapter->loadFile('/var/www/html/c...')\n#1 /var/www/html/cockpit/lib/vendor/ksubileau/color-thief-php/lib/ColorThief/ColorThief.php(177): ColorThief\\Image\\ImageLoader->load('/var/www/html/c...')\n#2 /var/www/html/cockpit/lib/vendor/ksubileau/color-thief-php/lib/ColorThief/ColorThief.php(136): ColorThief\\ColorThief::loadImage('/var/www/html/c...', 600, NULL)\n#3 /var/www/html/cockpit/modules/Cockpit/module/assets.php(65): ColorThief\\ColorThief::getPalette('/var/www/html/c...', 5, 600)\n#4 [internal function]: Lime\\Module->{closure}(Array)\n#5 /var/www/html/cockpit/lib/Lime/App.php(1495): call_user_func_array(Object(Closure), Array)\n#6 /var/www/html/cockpit/modules/Cock in /var/www/html/cockpit/lib/vendor/ksubileau/color-thief-php/lib/ColorThief/Image/Adapter/GDImageAdapter.php on line 43, referer: http://104.248.74.242/cockpit/collections/entry/items```

**Comment by JonSnowbd** [comment]
Was an issue with outdated software, fixed after pulling to `origin/master` instead of next and `sudo apt upgrade`.
